import 'package:hive_flutter/hive_flutter.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'dart:async';
import '../models/ride.dart';
import '../models/ledger_entry.dart';
import '../models/account_transfer.dart';
import '../models/pending_fuel_allocation.dart';
import '../models/refuel.dart';
import '../models/pending_tips.dart';
import '../models/account_balance.dart';
import '../utils/debug_logger.dart';

// Import adapters (they are generated in the .g.dart files which are part of the model files)
// The adapters are accessible after importing the models

class LocalStorageService {
  static final LocalStorageService _instance = LocalStorageService._internal();
  factory LocalStorageService() => _instance;
  LocalStorageService._internal();

  final FirebaseAuth _auth = FirebaseAuth.instance;
  
  // Hive box names - prefixed with userId
  String get _userId => _auth.currentUser?.uid ?? 'default';
  
  String get _ridesBoxName => 'rides_$_userId';
  String get _accountBalancesBoxName => 'accountBalances_$_userId';
  String get _ledgerBoxName => 'ledger_$_userId';
  String get _transfersBoxName => 'transfers_$_userId';
  String get _fuelAllocationBoxName => 'fuelAllocation_$_userId';
  String get _refuelsBoxName => 'refuels_$_userId';
  String get _pendingTipsBoxName => 'pendingTips_$_userId';

  // Box references
  Box<Ride>? _ridesBox;
  Box<AccountBalance>? _accountBalancesBox;
  Box<LedgerEntry>? _ledgerBox;
  Box<AccountTransfer>? _transfersBox;
  Box<PendingFuelAllocation>? _fuelAllocationBox;
  Box<Refuel>? _refuelsBox;
  Box<PendingTips>? _pendingTipsBox;

  bool _initialized = false;

  // Initialize all Hive boxes
  static Future<void> initialize() async {
    final instance = LocalStorageService();
    if (instance._initialized) return;

    try {
      // Register Hive adapters (will be generated by build_runner)
      if (!Hive.isAdapterRegistered(0)) {
        Hive.registerAdapter(RideStatusAdapter());
      }
      if (!Hive.isAdapterRegistered(1)) {
        Hive.registerAdapter(RideAdapter());
      }
      if (!Hive.isAdapterRegistered(2)) {
        Hive.registerAdapter(TransactionTypeAdapter());
      }
      if (!Hive.isAdapterRegistered(3)) {
        Hive.registerAdapter(TransactionCategoryAdapter());
      }
      if (!Hive.isAdapterRegistered(4)) {
        Hive.registerAdapter(TransactionNatureAdapter());
      }
      if (!Hive.isAdapterRegistered(5)) {
        Hive.registerAdapter(LedgerEntryAdapter());
      }
      if (!Hive.isAdapterRegistered(6)) {
        Hive.registerAdapter(AccountTransferAdapter());
      }
      if (!Hive.isAdapterRegistered(7)) {
        Hive.registerAdapter(PendingFuelAllocationAdapter());
      }
      if (!Hive.isAdapterRegistered(8)) {
        Hive.registerAdapter(RefuelAdapter());
      }
      if (!Hive.isAdapterRegistered(9)) {
        Hive.registerAdapter(PendingTipsAdapter());
      }
      if (!Hive.isAdapterRegistered(10)) {
        Hive.registerAdapter(AccountBalanceAdapter());
      }

      // Open boxes
      instance._ridesBox = await Hive.openBox<Ride>(instance._ridesBoxName);
      instance._accountBalancesBox = await Hive.openBox<AccountBalance>(instance._accountBalancesBoxName);
      instance._ledgerBox = await Hive.openBox<LedgerEntry>(instance._ledgerBoxName);
      instance._transfersBox = await Hive.openBox<AccountTransfer>(instance._transfersBoxName);
      instance._fuelAllocationBox = await Hive.openBox<PendingFuelAllocation>(instance._fuelAllocationBoxName);
      instance._refuelsBox = await Hive.openBox<Refuel>(instance._refuelsBoxName);
      instance._pendingTipsBox = await Hive.openBox<PendingTips>(instance._pendingTipsBoxName);

      instance._initialized = true;
      DebugLogger.log('LocalStorageService initialized');
    } catch (e) {
      DebugLogger.logError('Error initializing LocalStorageService: $e');
      rethrow;
    }
  }

  // Ensure boxes are open
  Future<void> _ensureBoxesOpen() async {
    if (!_initialized) {
      await initialize();
    }
  }

  // ==================== RIDES ====================

  Future<void> saveRide(Ride ride) async {
    await _ensureBoxesOpen();
    await _ridesBox!.put(ride.id, ride);
    DebugLogger.log('Ride saved: ${ride.id}');
  }

  Future<Ride?> getRide(String id) async {
    await _ensureBoxesOpen();
    return _ridesBox!.get(id);
  }

  Future<List<Ride>> getAllRides() async {
    await _ensureBoxesOpen();
    return _ridesBox!.values.toList();
  }

  Future<List<Ride>> getRidesByStatus(RideStatus status) async {
    await _ensureBoxesOpen();
    return _ridesBox!.values.where((ride) => ride.status == status).toList();
  }

  Future<Ride?> getActiveRide() async {
    await _ensureBoxesOpen();
    try {
      return _ridesBox!.values.firstWhere(
        (ride) => ride.status == RideStatus.active,
      );
    } catch (e) {
      return null;
    }
  }

  Stream<Ride?> getActiveRideStream() {
    _ensureBoxesOpen();
    return _ridesBox!.watch(key: null).map((event) {
      final rides = _ridesBox!.values.where((r) => r.status == RideStatus.active).toList();
      return rides.isEmpty ? null : rides.first;
    });
  }

  Stream<List<Ride>> getRidesStream() {
    _ensureBoxesOpen();
    return _ridesBox!.watch().map((event) => _ridesBox!.values.toList());
  }

  Future<List<Ride>> getRidesByDateRange(DateTime start, DateTime end) async {
    await _ensureBoxesOpen();
    return _ridesBox!.values.where((ride) {
      return ride.startTime.isAfter(start.subtract(const Duration(days: 1))) &&
             ride.startTime.isBefore(end.add(const Duration(days: 1)));
    }).toList();
  }

  Future<void> deleteRide(String id) async {
    await _ensureBoxesOpen();
    await _ridesBox!.delete(id);
    DebugLogger.log('Ride deleted: $id');
  }

  // ==================== ACCOUNT BALANCES ====================

  Future<void> saveAccountBalance(AccountBalance balance) async {
    await _ensureBoxesOpen();
    await _accountBalancesBox!.put(balance.accountId, balance);
    DebugLogger.log('Account balance saved: ${balance.accountId}');
  }

  Future<AccountBalance?> getAccountBalance(String accountId) async {
    await _ensureBoxesOpen();
    return _accountBalancesBox!.get(accountId);
  }

  Future<Map<String, double>> getAllAccountBalances() async {
    await _ensureBoxesOpen();
    final Map<String, double> balances = {};
    for (var key in _accountBalancesBox!.keys) {
      final balance = _accountBalancesBox!.get(key);
      if (balance != null) {
        balances[balance.accountId] = balance.balance;
      }
    }
    return balances;
  }

  Future<Map<String, AccountBalance>> getAllAccountBalanceObjects() async {
    await _ensureBoxesOpen();
    final Map<String, AccountBalance> balances = {};
    for (var key in _accountBalancesBox!.keys) {
      final balance = _accountBalancesBox!.get(key);
      if (balance != null) {
        balances[balance.accountId] = balance;
      }
    }
    return balances;
  }

  Stream<Map<String, double>> getAccountBalancesStream() {
    _ensureBoxesOpen();
    // Helper to get current balances
    Map<String, double> getCurrentBalances() {
      final Map<String, double> balances = {};
      for (var key in _accountBalancesBox!.keys) {
        final balance = _accountBalancesBox!.get(key);
        if (balance != null) {
          balances[balance.accountId] = balance.balance;
        }
      }
      return balances;
    }
    
    // Emit current state immediately, then watch for changes
    // Combine initial value with watch stream
    final initialValue = Stream.value(getCurrentBalances());
    final watchStream = _accountBalancesBox!.watch().map((event) => getCurrentBalances());
    
    // Merge initial value with watch stream
    return Stream.multi((controller) {
      // First emit current state
      controller.add(getCurrentBalances());
      
      // Then subscribe to watch stream
      final subscription = watchStream.listen(
        (balances) => controller.add(balances),
        onError: controller.addError,
        onDone: controller.close,
      );
      
      // Cancel subscription when controller is closed
      controller.onCancel = () {
        subscription.cancel();
      };
    });
  }

  Future<void> updateAccountBalance(String accountId, double newBalance) async {
    await _ensureBoxesOpen();
    final existing = await getAccountBalance(accountId);
    if (existing != null) {
      final updated = existing.copyWith(
        balance: newBalance,
        lastUpdated: DateTime.now(),
      );
      await saveAccountBalance(updated);
    }
  }

  // ==================== LEDGER ENTRIES ====================

  Future<void> saveLedgerEntry(LedgerEntry entry) async {
    await _ensureBoxesOpen();
    await _ledgerBox!.put(entry.id, entry);
    DebugLogger.log('Ledger entry saved: ${entry.id}');
  }

  Future<LedgerEntry?> getLedgerEntry(String id) async {
    await _ensureBoxesOpen();
    return _ledgerBox!.get(id);
  }

  Future<List<LedgerEntry>> getAllLedgerEntries() async {
    await _ensureBoxesOpen();
    return _ledgerBox!.values.toList();
  }

  Future<List<LedgerEntry>> getLedgerEntriesByAccount(String accountId) async {
    await _ensureBoxesOpen();
    return _ledgerBox!.values
        .where((entry) => entry.accountId == accountId)
        .toList();
  }

  Future<List<LedgerEntry>> getLedgerEntriesByRide(String rideId) async {
    await _ensureBoxesOpen();
    return _ledgerBox!.values
        .where((entry) => entry.rideId == rideId)
        .toList();
  }

  Future<List<LedgerEntry>> getRecentLedgerEntries({int limit = 50}) async {
    await _ensureBoxesOpen();
    final entries = _ledgerBox!.values.toList();
    entries.sort((a, b) => b.timestamp.compareTo(a.timestamp));
    return entries.take(limit).toList();
  }

  Stream<List<LedgerEntry>> getLedgerEntriesStream() {
    _ensureBoxesOpen();
    return _ledgerBox!.watch().map((event) => _ledgerBox!.values.toList());
  }

  Future<void> deleteLedgerEntry(String id) async {
    await _ensureBoxesOpen();
    await _ledgerBox!.delete(id);
    DebugLogger.log('Ledger entry deleted: $id');
  }

  // ==================== ACCOUNT TRANSFERS ====================

  Future<void> saveTransfer(AccountTransfer transfer) async {
    await _ensureBoxesOpen();
    await _transfersBox!.put(transfer.id, transfer);
    DebugLogger.log('Transfer saved: ${transfer.id}');
  }

  Future<AccountTransfer?> getTransfer(String id) async {
    await _ensureBoxesOpen();
    return _transfersBox!.get(id);
  }

  Future<List<AccountTransfer>> getAllTransfers() async {
    await _ensureBoxesOpen();
    return _transfersBox!.values.toList();
  }

  Future<List<AccountTransfer>> getRecentTransfers({int limit = 50}) async {
    await _ensureBoxesOpen();
    final transfers = _transfersBox!.values.toList();
    transfers.sort((a, b) => b.timestamp.compareTo(a.timestamp));
    return transfers.take(limit).toList();
  }

  Stream<List<AccountTransfer>> getTransfersStream() {
    _ensureBoxesOpen();
    return _transfersBox!.watch().map((event) => _transfersBox!.values.toList());
  }

  Future<void> deleteTransfer(String id) async {
    await _ensureBoxesOpen();
    await _transfersBox!.delete(id);
    DebugLogger.log('Transfer deleted: $id');
  }

  // ==================== PENDING FUEL ALLOCATION ====================

  Future<void> saveFuelAllocation(PendingFuelAllocation allocation) async {
    await _ensureBoxesOpen();
    await _fuelAllocationBox!.put(allocation.id, allocation);
    DebugLogger.log('Fuel allocation saved: ${allocation.id}');
  }

  Future<PendingFuelAllocation?> getFuelAllocation(String id) async {
    await _ensureBoxesOpen();
    return _fuelAllocationBox!.get(id);
  }

  Future<PendingFuelAllocation?> getPendingFuelAllocation() async {
    await _ensureBoxesOpen();
    if (_fuelAllocationBox!.isEmpty) return null;
    return _fuelAllocationBox!.values.first;
  }

  Stream<PendingFuelAllocation?> getPendingFuelAllocationStream() {
    _ensureBoxesOpen();
    return _fuelAllocationBox!.watch().map((event) {
      if (_fuelAllocationBox!.isEmpty) return null;
      return _fuelAllocationBox!.values.first;
    });
  }

  Future<void> deleteFuelAllocation(String id) async {
    await _ensureBoxesOpen();
    await _fuelAllocationBox!.delete(id);
    DebugLogger.log('Fuel allocation deleted: $id');
  }

  Future<void> clearPendingFuelAllocation() async {
    await _ensureBoxesOpen();
    await _fuelAllocationBox!.clear();
    DebugLogger.log('Fuel allocation cleared');
  }

  // ==================== REFUELS ====================

  Future<void> saveRefuel(Refuel refuel) async {
    await _ensureBoxesOpen();
    final id = refuel.id ?? DateTime.now().millisecondsSinceEpoch.toString();
    await _refuelsBox!.put(id, refuel.copyWith(id: id));
    DebugLogger.log('Refuel saved: $id');
  }

  Future<Refuel?> getRefuel(String id) async {
    await _ensureBoxesOpen();
    return _refuelsBox!.get(id);
  }

  Future<List<Refuel>> getAllRefuels() async {
    await _ensureBoxesOpen();
    final refuels = _refuelsBox!.values.toList();
    refuels.sort((a, b) => b.timestamp.compareTo(a.timestamp));
    return refuels;
  }

  Stream<List<Refuel>> getRefuelsStream() {
    _ensureBoxesOpen();
    return _refuelsBox!.watch().map((event) {
      final refuels = _refuelsBox!.values.toList();
      refuels.sort((a, b) => b.timestamp.compareTo(a.timestamp));
      return refuels;
    });
  }

  Future<void> deleteRefuel(String id) async {
    await _ensureBoxesOpen();
    await _refuelsBox!.delete(id);
    DebugLogger.log('Refuel deleted: $id');
  }

  // ==================== PENDING TIPS ====================

  Future<void> savePendingTips(PendingTips tips) async {
    await _ensureBoxesOpen();
    await _pendingTipsBox!.put(tips.id, tips);
    DebugLogger.log('Pending tips saved: ${tips.id}');
  }

  Future<PendingTips?> getPendingTips(String id) async {
    await _ensureBoxesOpen();
    return _pendingTipsBox!.get(id);
  }

  Future<PendingTips?> getCurrentPendingTips() async {
    await _ensureBoxesOpen();
    if (_pendingTipsBox!.isEmpty) return null;
    return _pendingTipsBox!.values.first;
  }

  Stream<PendingTips?> getPendingTipsStream() {
    _ensureBoxesOpen();
    return _pendingTipsBox!.watch().map((event) {
      if (_pendingTipsBox!.isEmpty) return null;
      return _pendingTipsBox!.values.first;
    });
  }

  Future<void> deletePendingTips(String id) async {
    await _ensureBoxesOpen();
    await _pendingTipsBox!.delete(id);
    DebugLogger.log('Pending tips deleted: $id');
  }

  Future<void> clearPendingTips() async {
    await _ensureBoxesOpen();
    await _pendingTipsBox!.clear();
    DebugLogger.log('Pending tips cleared');
  }

  // ==================== UTILITY METHODS ====================

  Future<bool> hasLocalData() async {
    await _ensureBoxesOpen();
    return _ridesBox!.isNotEmpty ||
           _accountBalancesBox!.isNotEmpty ||
           _ledgerBox!.isNotEmpty ||
           _transfersBox!.isNotEmpty ||
           _fuelAllocationBox!.isNotEmpty ||
           _refuelsBox!.isNotEmpty ||
           _pendingTipsBox!.isNotEmpty;
  }

  Future<void> clearAllData() async {
    await _ensureBoxesOpen();
    await _ridesBox!.clear();
    await _accountBalancesBox!.clear();
    await _ledgerBox!.clear();
    await _transfersBox!.clear();
    await _fuelAllocationBox!.clear();
    await _refuelsBox!.clear();
    await _pendingTipsBox!.clear();
    DebugLogger.log('All local data cleared');
  }
}

